# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 516353109409b92e7bcf5c72881b78d418f889eabda01630f972f4f3162593095fd0b400a487355c74c668dbc3f475984c80311298f662d5485cccb746a10b54

test:
  secret_key_base: 807ec340c4aefc9bfa0be689606654043d905a326b9c19f20c74c1644d4be7912ea05eecac459fe42c8b773b1eeb763ad3b6fb6dc8fd6a72f7a1e534bf7bdb46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
